name: train-game-security-pipeline

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  dependency-security-fe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - name: Run Snyk to check for dependency vulnerabilities
        run: snyk test --severity-threshold=high --file=client/package.json
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
  code-security-fe:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: snyk/actions/setup@master
      - name: Run Snyk to check for code vulnerabilities
        run: snyk code test --severity-threshold=high --file=client/package.json
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
          
  dependency-security-be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for dependency vulnerabilities
        uses: snyk/actions/maven-3-jdk-17@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --file=server/pom.xml

          
  code-security-be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for code vulnerabilities
        uses: snyk/actions/maven-3-jdk-17@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --file=server/pom.xml
          command: code test
