name: train-game-security-pipeline

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  snyk-fe:
    runs-on: ubuntu-latest
    steps:
      - name: Install packages
        uses: github/codeql-action/upload-sarif@v2
      - uses: actions/checkout@master
      - uses: actions/setup-node@v3
      - run: npm insall
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --sarif-file-output=snyk-fe.sarif --file=client/package.json
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-fe.sarif
          
  snyk-be:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/maven-3-jdk-17@master
        continue-on-error: true # To make sure that SARIF upload gets called
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --severity-threshold=high --sarif-file-output=snyk-be.sarif --file=server/pom.xml
      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: snyk-be.sarif
