name: train-game-security-pipeline

on:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

  dependency-security:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Run Snyk to check for dependency vulnerabilities
        run: npx snyk test --severity-threshold=high --all-projects --org=project-train-game
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  code-security:
    needs: checkout
    runs-on: ubuntu-latest
    steps:
      - name: Run Snyk to check for code vulnerabilities
        run: npx snyk code test --severity-threshold=high --all-projects --org=project-train-game
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  monitor:
    if: always()
    needs: [dependency-security, code-security]
    runs-on: ubuntu-latest
    steps:
      - name: Submit dependency security results to Snyk
        run: npx snyk monitor --all-projects --org=project-train-game
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Submit code security results to Snyk
        run: npx snyk code monitor --all-projects --org=project-train-game
        env:
           SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
